name: deploy-aks-automatic
on:
 workflow_dispatch:
 
permissions:
  id-token: write
  contents: read
  
jobs:
  deploy-aks-automatic:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v6.0.2

        - name: Azure Login
          uses: Azure/login@v3
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            
        - name: deploy-aks-echo1
          run:  echo "Set Environment Variables"
           
        - name: deploy-aks-echo2
          run: |
             ls ${{github.workspace}}
             echo ${AZURE_CLIENT_ID}
             echo ${AZURE_SUBSCRIPTION_ID}
             echo ${AZURE_TENANT_ID}
             echo ${VNET_NAME}
             echo ${RG_NAME}

        - name: deploy-aks1
          run: |
            ${{github.workspace}}/automatic/custom-network/private/sh/define-vars.sh
          
    
