# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Run Azure Login with OIDC
on: [push]
 workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checking out repo code'
        uses: actions/checkout@v6
      
      - name: 'Az CLI login'
        uses: azure/login@8c334a195cbb38e46038007b304988d888bf676a
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Run az commands'
        run: |
          az account show
          az group list

      - name: 'Set ENV Variables'
        run: |          
         RG_NAME=automatic-rg
         VNET_NAME=automatic-vnet
         CLUSTER_NAME=automatic
         IDENTITY_NAME=automatic-uami
         LOCATION=eastus
         SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}
          echo "${RG_NAME} -l ${LOCATION} ${IDENTITY_NAME} ${CLUSTER_NAME}"
          automatic/custom-network/public/sh/create-rg.sh ${RG_NAME} ${LOCATION}          
          automatic/custom-network/public/sh/create-vnet.sh ${RG_NAME} ${LOCATION} ${VNET_NAME}
          automatic/custom-network/public/sh/create-uami.sh ${RG_NAME} ${LOCATION} ${VNET_NAME} ${IDENTITY_NAME}
          automatic/custom-network/public/sh/create-aks.sh ${RG_NAME} ${LOCATION} ${VNET_NAME} ${IDENTITY_NAME} ${CLUSTER_NAME}

